import { downloadZip } from "./zipUtils";

export function downloadPortfolioZip(resume, theme = "aurora", userAvatar = "") {
  const personalInfo = resume.personalInfo || {};
  const fullName = personalInfo.fullName || "John Doe";
  const email = personalInfo.email || "";
  const phone = personalInfo.phone || "";
  const location = personalInfo.location || "";
  const bio = personalInfo.summary || "Full Stack Developer passionate about building high-performance web applications.";
  const experience = resume.experience || [];
  const education = resume.education || [];
  const skills = resume.skills || [];
  const projects = resume.projects || [];
  const avatar = userAvatar || `https://api.dicebear.com/7.x/adventurer/svg?seed=${encodeURIComponent(fullName)}`;
  const targetRole = experience[0]?.position || "Full Stack Engineer";

  const resolvedTheme = theme === "auto" ? "aurora" : theme;

  const htmlContent = generateStandaloneHtml({
    fullName,
    email,
    phone,
    location,
    bio,
    targetRole,
    experience,
    education,
    skills,
    projects,
    avatar,
    theme: resolvedTheme,
  });

  const cssContent = generateThemeCss(resolvedTheme);

  const readmeContent = `# ${fullName} - Portfolio Website Code

This repository contains the standalone, production-ready source code for **${fullName}**'s personal web portfolio using the **${resolvedTheme.toUpperCase()}** theme.

## 📁 Files Included
- \`index.html\`: Complete responsive HTML5 structure with semantic sections and embedded content.
- \`style.css\`: Customized CSS stylesheet for the ${resolvedTheme} theme.
- \`README.md\`: Quick start instructions.

## 🚀 How to Run Locally
1. Double click \`index.html\` to open it directly in any web browser.

## 🌐 Deploy to GitHub Pages / Vercel / Netlify
1. Create a repository on GitHub.
2. Push \`index.html\` and \`style.css\` to your repo.
3. Turn on GitHub Pages under **Settings -> Pages**, or drag and drop this zip folder directly into [Netlify Drop](https://app.netlify.com/drop) or Vercel.

Generated by AstraCV.
`;

  const files = [
    { name: "index.html", content: htmlContent },
    { name: "style.css", content: cssContent },
    { name: "README.md", content: readmeContent },
  ];

  const zipFilename = `${fullName.toLowerCase().replace(/[^a-z0-9]/g, "-")}-portfolio-${resolvedTheme}.zip`;
  downloadZip(files, zipFilename);
}

function generateStandaloneHtml({
  fullName,
  email,
  phone,
  location,
  bio,
  targetRole,
  experience,
  education,
  skills,
  projects,
  avatar,
  theme,
}) {
  return `<!DOCTYPE html>
<html lang="en" class="${theme}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${fullName} - ${targetRole} Portfolio</title>
  <meta name="description" content="${fullName}'s personal web portfolio">
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;600&family=Inter:wght@400;600;800&family=Outfit:wght@400;700;900&family=Playfair+Display:ital,wght@0,600;1,600&family=Plus+Jakarta+Sans:wght@400;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
</head>
<body class="theme-body transition-colors duration-300">

  <!-- Header / Navigation -->
  <header class="theme-header sticky top-0 z-50 backdrop-blur-md border-b">
    <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
      <div class="font-extrabold text-xl tracking-tight">${fullName}</div>
      <nav class="hidden md:flex gap-8 text-sm font-semibold">
        <a href="#about" class="hover:opacity-80">About</a>
        ${experience.length > 0 ? '<a href="#experience" class="hover:opacity-80">Experience</a>' : ''}
        ${projects.length > 0 ? '<a href="#projects" class="hover:opacity-80">Projects</a>' : ''}
        ${skills.length > 0 ? '<a href="#skills" class="hover:opacity-80">Skills</a>' : ''}
        <a href="#contact" class="hover:opacity-80">Contact</a>
      </nav>
      <a href="#contact" class="theme-btn-primary px-5 py-2 rounded-xl font-bold text-xs">Contact Me</a>
    </div>
  </header>

  <!-- Hero Section -->
  <section id="hero" class="max-w-6xl mx-auto px-6 py-20 grid md:grid-cols-12 gap-12 items-center min-h-[80vh]">
    <div class="md:col-span-7 space-y-6 text-left">
      <span class="theme-badge inline-block px-3 py-1 text-xs font-bold rounded-full">Available for Hire</span>
      <h1 class="text-4xl sm:text-6xl font-black leading-tight">Hi, I'm <span class="theme-highlight">${fullName}</span></h1>
      <h2 class="text-xl sm:text-2xl font-bold opacity-80">${targetRole}</h2>
      <p class="text-sm sm:text-base opacity-75 max-w-lg leading-relaxed">${bio}</p>
      <div class="pt-4 flex gap-4">
        <a href="#contact" class="theme-btn-primary px-6 py-3 rounded-xl font-extrabold text-sm">Get In Touch</a>
        ${projects.length > 0 ? '<a href="#projects" class="theme-btn-secondary px-6 py-3 rounded-xl font-bold text-sm">View Projects</a>' : ''}
      </div>
    </div>
    <div class="md:col-span-5 flex justify-center">
      <div class="theme-avatar-container p-3 rounded-3xl">
        <img src="${avatar}" alt="${fullName}" class="w-64 h-64 rounded-2xl object-cover">
      </div>
    </div>
  </section>

  ${experience.length > 0 ? `
  <!-- Experience Section -->
  <section id="experience" class="theme-section-alt py-20 border-t">
    <div class="max-w-6xl mx-auto px-6 space-y-12">
      <h2 class="text-3xl font-extrabold text-left">Work Experience</h2>
      <div class="space-y-8 text-left max-w-4xl">
        ${experience.map(exp => `
          <div class="theme-card p-6 rounded-2xl border space-y-2">
            <div class="flex justify-between items-center flex-wrap gap-2">
              <h3 class="text-lg font-bold">${exp.position || ''}</h3>
              <span class="text-xs font-mono opacity-60">${exp.startDate ? exp.startDate.substring(0,4) : ''} - ${exp.currentlyWorking ? 'Present' : (exp.endDate ? exp.endDate.substring(0,4) : '')}</span>
            </div>
            <p class="text-xs font-semibold opacity-80">${exp.company || ''} ${exp.location ? '• ' + exp.location : ''}</p>
            ${Array.isArray(exp.description) ? exp.description.map(b => `<p class="text-xs opacity-75 leading-relaxed">• ${b}</p>`).join('') : `<p class="text-xs opacity-75">${exp.description || ''}</p>`}
          </div>
        `).join('')}
      </div>
    </div>
  </section>
  ` : ''}

  ${education.length > 0 ? `
  <!-- Education Section -->
  <section id="education" class="py-16 border-t">
    <div class="max-w-6xl mx-auto px-6 space-y-8">
      <h2 class="text-3xl font-extrabold text-left">Education</h2>
      <div class="grid md:grid-cols-2 gap-6 text-left">
        ${education.map(edu => `
          <div class="theme-card p-6 rounded-2xl border space-y-2">
            <h3 class="text-lg font-bold">${edu.degree || ''}</h3>
            <p class="text-xs opacity-80">${edu.school || ''} ${edu.fieldOfStudy ? '• ' + edu.fieldOfStudy : ''}</p>
          </div>
        `).join('')}
      </div>
    </div>
  </section>
  ` : ''}

  ${projects.length > 0 ? `
  <!-- Projects Section -->
  <section id="projects" class="py-20 max-w-6xl mx-auto px-6 space-y-12">
    <h2 class="text-3xl font-extrabold text-left">Featured Projects</h2>
    <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 text-left">
      ${projects.map(proj => `
        <div class="theme-card p-6 rounded-2xl border space-y-4 flex flex-col justify-between">
          <div class="space-y-2">
            <h3 class="font-bold text-lg">${proj.title || 'Project'}</h3>
            <p class="text-xs opacity-75 leading-relaxed">${proj.description || ''}</p>
          </div>
          ${proj.technologies && proj.technologies.length > 0 ? `
            <div class="flex flex-wrap gap-1.5 pt-2">
              ${proj.technologies.map(tech => `<span class="theme-tag text-[10px] font-mono px-2 py-0.5 rounded">${tech}</span>`).join('')}
            </div>
          ` : ''}
        </div>
      `).join('')}
    </div>
  </section>
  ` : ''}

  ${skills.length > 0 ? `
  <!-- Skills Section -->
  <section id="skills" class="theme-section-alt py-16 border-y">
    <div class="max-w-6xl mx-auto px-6 space-y-6 text-left">
      <h2 class="text-2xl font-extrabold">Technical Skills</h2>
      <div class="flex flex-wrap gap-2.5">
        ${skills.map(skill => `<span class="theme-skill-pill px-4 py-2 rounded-xl text-xs font-bold border">${skill}</span>`).join('')}
      </div>
    </div>
  </section>
  ` : ''}

  <!-- Contact Section -->
  <section id="contact" class="max-w-4xl mx-auto px-6 py-20 text-left">
    <div class="theme-card p-8 rounded-3xl border space-y-6">
      <h2 class="text-3xl font-extrabold">Get In Touch</h2>
      <div class="space-y-2 text-xs opacity-80">
        ${email ? `<p><strong>Email:</strong> ${email}</p>` : ''}
        ${phone ? `<p><strong>Phone:</strong> ${phone}</p>` : ''}
        ${location ? `<p><strong>Location:</strong> ${location}</p>` : ''}
      </div>
      <form onsubmit="event.preventDefault(); alert('Message sent successfully!'); this.reset();" class="space-y-4 pt-2">
        <input type="text" placeholder="Your Name" required class="w-full px-4 py-2.5 rounded-xl border bg-transparent text-sm focus:outline-none">
        <input type="email" placeholder="Your Email" required class="w-full px-4 py-2.5 rounded-xl border bg-transparent text-sm focus:outline-none">
        <textarea placeholder="Your Message..." rows="4" required class="w-full px-4 py-2.5 rounded-xl border bg-transparent text-sm focus:outline-none"></textarea>
        <button type="submit" class="theme-btn-primary w-full py-3 rounded-xl font-bold text-sm">Send Message</button>
      </form>
    </div>
  </section>

  <!-- Footer -->
  <footer class="py-8 text-center text-xs opacity-50 border-t">
    <p>&copy; ${new Date().getFullYear()} ${fullName}. All rights reserved.</p>
  </footer>

</body>
</html>
`;
}

function generateThemeCss(theme) {
  if (theme === "aurora") {
    return `
body.aurora {
  background-color: #0b0f19;
  color: #f1f5f9;
  font-family: 'Outfit', sans-serif;
}
.aurora .theme-header { background: rgba(11, 15, 25, 0.85); border-color: #1e293b; }
.aurora .theme-highlight { background: linear-gradient(to right, #22d3ee, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.aurora .theme-badge { background: rgba(6, 182, 212, 0.15); color: #22d3ee; border: 1px solid rgba(6, 182, 212, 0.3); }
.aurora .theme-btn-primary { background: #22d3ee; color: #0b0f19; }
.aurora .theme-btn-secondary { background: #1e293b; color: #cbd5e1; border: 1px solid #334155; }
.aurora .theme-card { background: rgba(15, 23, 42, 0.7); border-color: #1e293b; }
.aurora .theme-section-alt { background: rgba(15, 23, 42, 0.4); border-color: #1e293b; }
.aurora .theme-tag { background: rgba(6, 182, 212, 0.1); color: #22d3ee; border: 1px solid rgba(6, 182, 212, 0.2); }
.aurora .theme-skill-pill { background: #0f172a; color: #22d3ee; border-color: #1e293b; }
.aurora .theme-avatar-container { background: rgba(15, 23, 42, 0.6); border: 1px solid rgba(6, 182, 212, 0.3); }
`;
  }

  if (theme === "editorial") {
    return `
body.editorial {
  background-color: #faf8f5;
  color: #1c1917;
  font-family: 'Playfair Display', Georgia, serif;
}
.editorial .theme-header { background: rgba(250, 248, 245, 0.9); border-color: rgba(120, 113, 108, 0.2); }
.editorial .theme-highlight { color: #78350f; font-style: italic; }
.editorial .theme-badge { background: #fef3c7; color: #92400e; }
.editorial .theme-btn-primary { background: #1c1917; color: #ffffff; border-radius: 0; }
.editorial .theme-btn-secondary { background: transparent; color: #1c1917; border: 1px solid #1c1917; border-radius: 0; }
.editorial .theme-card { background: #ffffff; border-color: #e7e5e4; border-radius: 0; }
.editorial .theme-section-alt { background: #ffffff; border-color: #e7e5e4; }
.editorial .theme-tag { background: #f5f5f4; color: #44403c; }
.editorial .theme-skill-pill { background: #ffffff; color: #1c1917; border-color: #d6d3d1; border-radius: 0; }
.editorial .theme-avatar-container { background: #ffffff; border: 2px solid #78350f; border-radius: 50%; }
`;
  }

  if (theme === "brutalist") {
    return `
body.brutalist {
  background-color: #fef3c7;
  color: #0f172a;
  font-family: 'Outfit', sans-serif;
}
.brutalist .theme-header { background: #ffffff; border-bottom: 4px solid #000000; }
.brutalist .theme-highlight { background: #67e8f9; padding: 0 8px; border: 2px solid #000; box-shadow: 3px 3px 0px 0px #000; }
.brutalist .theme-badge { background: #f472b6; color: #000000; border: 2px solid #000; box-shadow: 2px 2px 0px 0px #000; }
.brutalist .theme-btn-primary { background: #a3e635; color: #000000; border: 3px solid #000; box-shadow: 4px 4px 0px 0px #000; border-radius: 0; }
.brutalist .theme-btn-secondary { background: #ffffff; color: #000000; border: 3px solid #000; box-shadow: 4px 4px 0px 0px #000; border-radius: 0; }
.brutalist .theme-card { background: #ffffff; border: 3px solid #000000; box-shadow: 6px 6px 0px 0px #000000; border-radius: 0; }
.brutalist .theme-section-alt { background: #ffffff; border-color: #000000; }
.brutalist .theme-tag { background: #c084fc; color: #000000; border: 1px solid #000; }
.brutalist .theme-skill-pill { background: #ffffff; color: #000000; border: 2px solid #000; box-shadow: 3px 3px 0px 0px #000; border-radius: 0; }
.brutalist .theme-avatar-container { background: #c084fc; border: 4px solid #000; box-shadow: 6px 6px 0px 0px #000; }
`;
  }

  if (theme === "terminal") {
    return `
body.terminal {
  background-color: #0d1117;
  color: #c9d1d9;
  font-family: 'Fira Code', monospace;
}
.terminal .theme-header { background: #161b22; border-color: #30363d; }
.terminal .theme-highlight { color: #34d399; }
.terminal .theme-badge { background: #161b22; color: #34d399; border: 1px solid #30363d; }
.terminal .theme-btn-primary { background: #10b981; color: #000000; border-radius: 4px; }
.terminal .theme-btn-secondary { background: #161b22; color: #c9d1d9; border: 1px solid #30363d; border-radius: 4px; }
.terminal .theme-card { background: #161b22; border-color: #30363d; border-radius: 6px; }
.terminal .theme-section-alt { background: rgba(22, 27, 34, 0.5); border-color: #30363d; }
.terminal .theme-tag { background: #0d1117; color: #38bdf8; border: 1px solid #30363d; }
.terminal .theme-skill-pill { background: #0d1117; color: #34d399; border-color: #30363d; border-radius: 4px; }
.terminal .theme-avatar-container { background: #161b22; border: 1px solid #30363d; }
`;
  }

  if (theme === "swiss") {
    return `
body.swiss {
  background-color: #ffffff;
  color: #020617;
  font-family: 'Plus Jakarta Sans', sans-serif;
}
.swiss .theme-header { background: #ffffff; border-color: #020617; }
.swiss .theme-highlight { color: #2563eb; }
.swiss .theme-badge { background: #020617; color: #ffffff; border-radius: 0; }
.swiss .theme-btn-primary { background: #2563eb; color: #ffffff; border-radius: 0; }
.swiss .theme-btn-secondary { background: #ffffff; color: #020617; border: 2px solid #020617; border-radius: 0; }
.swiss .theme-card { background: #ffffff; border: 2px solid #020617; border-radius: 0; }
.swiss .theme-section-alt { background: #f8fafc; border-color: #020617; }
.swiss .theme-tag { background: #f1f5f9; color: #020617; }
.swiss .theme-skill-pill { background: #ffffff; color: #020617; border: 1px solid #020617; border-radius: 0; }
.swiss .theme-avatar-container { background: #f1f5f9; border: 2px solid #020617; }
`;
  }

  // Sunset default
  return `
body.sunset {
  background-color: #020617;
  color: #f8fafc;
  font-family: 'Outfit', sans-serif;
}
.sunset .theme-header { background: rgba(2, 6, 23, 0.85); border-color: #1e293b; }
.sunset .theme-highlight { background: linear-gradient(to right, #f59e0b, #f43f5e, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.sunset .theme-badge { background: rgba(244, 63, 94, 0.15); color: #fb7185; border: 1px solid rgba(244, 63, 94, 0.3); }
.sunset .theme-btn-primary { background: linear-gradient(to right, #f59e0b, #f43f5e); color: #ffffff; }
.sunset .theme-btn-secondary { background: #0f172a; color: #f1f5f9; border: 1px solid #334155; }
.sunset .theme-card { background: #0f172a; border-color: #1e293b; }
.sunset .theme-section-alt { background: rgba(15, 23, 42, 0.5); border-color: #1e293b; }
.sunset .theme-tag { background: rgba(244, 63, 94, 0.1); color: #fb7185; }
.sunset .theme-skill-pill { background: #0f172a; color: #fca5a5; border-color: #334155; }
.sunset .theme-avatar-container { background: #0f172a; border: 1px solid #f43f5e; }
`;
}
